version: "3.7"

services:
  php:
    build:
      context: .
      target: app_php_dev
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://p2p:p2p@database:5432/p2p?serverVersion=${POSTGRES_VERSION:-14}
      APP_ENV: dev
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=192.168.1.112"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: p2p
      # You should definitely change the password in production
      POSTGRES_PASSWORD: p2p
      POSTGRES_USER: p2p
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db-data:
