version: "3.7"

services:
  php:
    build:
      context: .
      target: app_php_dev
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://p2p:p2p@database:5432/p2p?serverVersion=${POSTGRES_VERSION:-14}
      APP_ENV: dev
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=192.168.1.112"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9000:9000'
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: p2p
      POSTGRES_PASSWORD: p2p
      POSTGRES_USER: p2p
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8082:80'
    volumes:
      - ./:/srv/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
volumes:
  db-data:
